name: book_now_null_safety
description: A Hotel booking app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  dio: ^4.0.0
  get_storage: ^2.0.3
  font_awesome_flutter: ^9.1.0
  shimmer: ^2.0.0
  fancy_shimmer_image: ^2.0.0+2
  syncfusion_flutter_datepicker: ^19.2.59
  material_design_icons_flutter: ^5.0.5955-rc.1
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.3

flutter_native_splash:
  color: "#212843"
  image: images/logo_new.png
  android: true

flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Yanone
      fonts:
        - asset: fonts/Yanone.ttf

    - family: Signi
      fonts:
        - asset: fonts/Signi.ttf

    - family: Sansita
      fonts:
        - asset: fonts/Sansita-Regular.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: Urban
      fonts:
        - asset: fonts/Urbanist-Thin.ttf
          weight: 100
        - asset: fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: fonts/Urbanist-Light.ttf
          weight: 300
        - asset: fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: fonts/Urbanist-Black.ttf
          weight: 700
        - asset: fonts/Urbanist-Bold.ttf
          weight: 800
        - asset: fonts/Urbanist-ExtraBold.ttf
          weight: 900
